version: "3"

services:
  app:
    container_name: tagflip_backend
    restart: always
    build: .
    env_file:
      - docker.env
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - /opt/tagflip:/opt/tagflip
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - docker.env
    ports:
      - "127.0.0.1::3306"
      - "127.0.0.1::33060"
    volumes:
      - /opt/tagflip/db:/var/lib/mysql
